name: CI

on:
  push:
    branches:
      - 'main'
      - 'release-v**'
      - 'full-sonar-analysis-**'
  pull_request:

jobs:
  build:
    name: Build OS ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Config long names (Windows)
        if: matrix.os == 'windows-latest'
        run: git config --system core.longpaths true
        shell: cmd

      - name: Checkout powsybl-core branch
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: powsybl/powsybl-core
          ref: refs/heads/math_native_1_5_0
          path: core
          fetch-depth: 0

      - name: Build and install powsybl-core with Maven
        run: mvn --batch-mode -DskipTests=true --file ./core/pom.xml install

      - name: Build with Maven (Ubuntu / MacOS)
        if: matrix.os != 'windows-latest'
        run: ./mvnw --batch-mode -Pjacoco install

      - name: Build with Maven (Windows)
        if: matrix.os == 'windows-latest'
        run: mvnw.cmd --batch-mode install
        shell: cmd

      - name: Run SonarCloud analysis
        if: matrix.os == 'ubuntu-latest'
        run: >
          ./mvnw --batch-mode -DskipTests sonar:sonar
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.organization=powsybl-ci-github
          -Dsonar.projectKey=com.powsybl:powsybl-open-loadflow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
